name: GitHub CI CD

on:
  push:
    branches:    
      - development

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo ${{github.event.base_ref}}
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_SECRET_ID }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Create env file
        run: |
          cat > .env << EOF
          ${{ secrets.DEV_ENV }}
          EOF
      
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          tag=$(git rev-parse --short HEAD)
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:exapmle-web-frontend-$tag .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:example-web-frontend-$tag
       
      - name: Log out of Amazon ECR
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
  
  helm:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'hutfin'
          repository: 'k8s-deployment-helm'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Manupolation in Helm Chart
        run: |
          tag=$(git rev-parse --short HEAD)
          cd k8s-deployment-helm/example-web-frontend
          sed -i "s|tag:.*|tag:\ example-web-frontend-$tag|g" ./dev-values.yaml
          git config --global user.email "change-me@email.com"
          git config --global user.name "Change_Me"
          git add .
          git commit -m "docker image tag updated to example-web-frontend-$tag"
          git push origin main
  Deploy-on-EKS:
    needs: helm
    runs-on: ubuntu-latest

    steps:  
      - name: Setting Kubernets Configuration
        run: | 
          pip install awscli kubernetes
          aws --profile default configure set aws_access_key_id ${{ secrets.EKS_ACCESS_KEY }}
          aws --profile default configure set aws_secret_access_key ${{ secrets.EKS_ACCESS_SECRET_ID }}
          aws eks update-kubeconfig --name=hutfin-eks --region=us-east-1
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Deploy on Kubernetes
        uses: actions/checkout@v3
      - uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'GitHub-ORG-Name/github-username'
          repository: 'k8s-deployment-helm'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - name: Manipulation in Helm Chart
        run: |
          tag=$(git rev-parse --short HEAD)
          cd k8s-deployment-helm/example-web-frontend/
          export DEPLOY=$(helm  lint . -f dev-values.yaml | grep Error | wc -l)
          echo "deploy value is ${DEPLOY}"
          if [[ "${DEPLOY}" -eq 0 ]];
          then
            helm upgrade --install example-web-frontend . -f dev-values.yaml --create-namespace --namespace development --set image.tag=example-web-frontend-$tag
          else
            echo "deployment failed" && exit 1
          fi
          kubectl rollout status deployment example-web-frontend --namespace development;